format = """
[â•­â•¼â•â•¾ $username â•¼â•â•¾ $hostname â•¼â”€â•¼â”€â•¼â”€â•¼â”€â•¼â”€â•¼â”€â•¼â”€â•¼â”€â•¼â”€â•¼â”€â•¼â”€î«î‚µ](yellow) $cmd_duration
[â•â•¾î« ](yellow)$directory$git_branch$git_commit$git_state$git_status$hg_branch
[â•°â•¾](yellow) $character"""

[directory]
truncation_length = 2
truncation_symbol = "î—¾ "
style = "bold #7abef5"
read_only = "ï€£"
disabled = false

[username]
style_user = "bold #ff9e4f"
style_root = "bold #eb4972"
show_always = true
format = "[$user]($style)"
disabled = false

[hostname]
ssh_only = false
format = "[$hostname]($style)"
trim_at = "."
style = "bold yellow"
disabled = false

[character]
success_symbol = "[â—ˆ](bold yellow)"
error_symbol = "[â—ˆ](bold red)"
disabled = false

[cmd_duration]
min_time = 420
show_milliseconds = false
format = "[$duration](bold yellow)"
disabled = false

[git_branch]
truncation_length = 12
style = "bold #b0d0eb"
truncation_symbol = "..."
disabled = false

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "
tag_disabled = false
only_detached = true

[git_status]
format = '([\[$conflicted$stashed$modified$staged$untracked$renamed$deleted$ahead$diverged$behind\]]($style) )'
conflicted = "ï²… "
stashed = "ïš’ "
modified = "ï ‹ "
staged = '[ï— $count ](bold green)'
untracked = '[â€î $count](bold #f0dd86)'
renamed = "î‰˜ "
deleted = "ï‡¸ "
ahead = '[ïœ ${count}](bold #57d9c3)'
diverged = '[ï—º ](bold purple)'
behind = '[ï¥ ${count}](bold #eb4972)'

style = "bold #cedeeb"